stages:
  - build
  - test
  - release

before_script:
  - printenv | sort

build:
  stage: build
  script:
    # - cp /usr/local/lib/darwin/{libSDL2-2.0.0,libSDL2_mixer-2.0.0}.dylib ./crossbuild/libSDL/
    # - ./crossbuild.sh
    - |
      VERSION=$(. ./bin/increment_version.sh ${VERSIONCOMPONENTTOINCREMENT} ${LASTVERSION})
      echo "${VERSION}" > version.txt
      echo "${VERSION}" > version-${VERSION}.txt
      echo "VERSION=${VERSION}" > version.env
      tar -czvf ${PACKAGENAME}.${VERSION}.tar.gz .
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${PACKAGENAME}.${VERSION}.tar.gz ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGENAME}/${VERSION}/${PACKAGENAME}.${VERSION}.tar.gz
  artifacts:
    reports:
      dotenv: version.env

# release:
#   stage: release
#   image: registry.gitlab.com/gitlab-org/release-cli:latest
#   script:
#     - echo 'release job'
#   release:
#     name: 'VVVVVV/rust release $CI_COMMIT_TAG'
#     description: 'Created using the release-cli'
#     tag_name: '$CI_COMMIT_TAG'                                     
#     ref: '$CI_COMMIT_TAG'
