stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - ln -s /usr/local/lib/darwin/libSDL2-2.0.0.dylib ./crossbuild/libSDL/
    - ln -s /usr/local/lib/darwin/libSDL2_mixer-2.0.0.dylib ./crossbuild/libSDL/
    - ls -al ./crossbuild/libSDL/
    - ./crossbuild.sh

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:v0.1.0
  script:
    - echo 'release job'
  release:
    name: 'VVVVVV/rust release $CI_COMMIT_TAG'
    description: 'Created using the release-cli'
    tag_name: '$CI_COMMIT_TAG'                                     
    ref: '$CI_COMMIT_TAG'
